systems:
  - name: steamer
    use: true
  - name: steamer600
    use: false
  - name: zips
    use: false
  - name: thebat
    use: false
  - name: atc
    use: false
  - name: fangraphsdc
    use: true
settings:
  teams: 12
  budget: 260
  roster:
    hitters:
      C: 1
      1B: 1
      2B: 1
      3B: 1
      SS: 1
      OF: 4
      UT: 1
      IF: 1
      MI: 0
      CI: 0
      RF: 0
      CF: 0
      LF: 0
    pitchers:
      SP: 2
      RP: 2
      P: 3
  categories:
    hitting:
      - key: AVG
        type: positive-ratio
      - key: R
        type: positive-count
      - key: RBI
        type: positive-count
      - key: HR
        type: positive-count
      - key: SB
        type: positive-count
      - key: OPS
        type: positive-ratio
    pitching:
      - key: W
        type: positive-count
      - key: L
        type: negative-count
      - key: K
        type: positive-count
      - key: SV
        type: positive-count
      - key: WHIP
        type: negative-ratio
      - key: ERA
        type: negative-ratio
